alias fsam='sshfs lansdell@americano.amath.washington.edu:/home2/lansdell /home/lansdell/remotes/americano'
alias fsbl='sshfs lansdell@bleen.seas.upenn.edu:/home/lansdell /Users/lansdell/remotes/bleen'
alias ufsam='sudo umount /home/lansdell/remotes/americano'
alias espresso='ssh lansdell@espresso.amath.washington.edu'
alias macchiato='ssh amathadm@macchiato.amath.washington.edu'
alias fairhall='ssh lansdell@fairhallcylinder.physiol.washington.edu'
alias latte='ssh lansdell@latte.amath.washington.edu'
alias bleen='mosh lansdell@bleen.seas.upenn.edu'
alias dolores='mosh lansdell@dolores.seas.upenn.edu'
alias quadcorn='mosh lansdell@quadcorn.seas.upenn.edu'
alias mocha='ssh lansdell@mocha.amath.washington.edu'
alias galao='ssh lansdell@galao.amath.washington.edu'
alias am='ssh lansdell@americano.amath.washington.edu'
alias amx='ssh lansdell@americano.amath.washington.edu -X'
alias espressos='ssh amathsys@espresso.amath.washington.edu'
alias lattes='ssh amathsys@latte.amath.washington.edu'
alias mochas='ssh amathsys@mocha.amath.washington.edu'
alias galaos='ssh amathsys@galao.amath.washington.edu'
alias ams='ssh amathsys@americano.amath.washington.edu'
alias stgamath='ssh stgamath@stgamath.ovid.u.washington.edu'
alias perses='ssh lansdell@perses.ms.unimelb.edu.au'
alias ovid='ssh lansdell@lansdell.ovid.u.washington.edu'
alias amath='ssh amath@amath.ovid.u.washington.edu'
alias vmail='ssh lansdell@vmail.cac.washington.edu'
alias masala='ssh amathsys@masala.amath.washington.edu'
alias eps2pdf='ps2pdf -dEPSCrop'
alias pylab='ipython --pylab'
alias emacs="emacs -nw"
alias todo='emacs ~/Dropbox/todo.org'
alias syslog='vim ~/Dropbox/sysadmin_logs/ben.log'
alias computing='vim ~/Dropbox/computing.log'
alias emails='emacs ~/Dropbox/emails.org'
alias now="emacs ~/Dropbox/now.org"
alias g="git"
alias gst="git st"
alias gad="git ad"
alias gci="git ci"
alias gco="git co"
alias gbr="git br"
alias gls="git ls"
alias gdi="git di"
alias gps="git ps"
alias gpl="git pl"
alias matlab="matlab -nodesktop"
alias sls="screen -list"
alias sr="screen -r"
alias tls="tmux ls"
alias tr="tmux attach -t"
alias tn="tmux new-session -t"
alias vgam="/opt/VirtualGL/bin/vglconnect -s lansdell@americano.amath.washington.edu"
alias fsdo="sshfs lansdell@doppio.amath.washington.edu:/home/lansdell /home/lansdell/remotes/doppio"
alias ufsdo="sudo umount /home/lansdell/remotes/doppio"
alias dp="ssh lansdell@doppio.amath.washington.edu"
alias dpx="ssh lansdell@doppio.amath.washington.edu -X"
alias nvs="nvidia-smi"
alias jnr="jupyter notebook --no-browser --port=8889 --ip='*' --NotebookApp.token='' --NotebookApp.password=''"
alias jnp="jupyter notebook --no-browser --ip='*' --NotebookApp.token='' --NotebookApp.password='' --port "
alias mountusb="sudo mount -t vfat /dev/sdc2 /home/lansdell/usbdrive/"
alias nvslost="sudo fuser -v /dev/nvidia*"
alias bleenjs="ssh -N -f -L localhost:8888:localhost:8889 lansdell@bleen.seas.upenn.edu"
alias bleenjs1="ssh -N -f -L localhost:8888:localhost:8890 lansdell@bleen.seas.upenn.edu"
alias jn="jupyter notebook"
alias kodiak="mosh kodiak"
alias ultra94="ssh blansdel@ultra94.stjude.org"
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias r="radian"
alias serveon="python3 -m http.server "
alias dud="du --max-depth 1 -h | sort -h"
alias zak="mosh splpzakgrp"
alias fullfs="sudo du -cha --max-depth=1 -x --one-file-system . | sort -h"